### ISSUE TITLE
bb2csv errors

### ISSUE THREAD

**Issue by mickhannam** [atomgomba/orangebox#4]
When I try and run bb2csv against my logfile I get the following error:

:~$ bb2csv -v BTFL_BLACKBOX_LOG_20200827_190605.BBL 
Traceback (most recent call last):
  File "/usr/local/bin/bb2csv", line 4, in <module>
    __import__('pkg_resources').run_script('orangebox==0.2.0', 'bb2csv')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/orangebox-0.2.0-py3.8.egg/EGG-INFO/scripts/bb2csv", line 57, in <module>
  File "/usr/local/lib/python3.8/dist-packages/orangebox-0.2.0-py3.8.egg/EGG-INFO/scripts/bb2csv", line 29, in main
  File "/usr/local/lib/python3.8/dist-packages/orangebox-0.2.0-py3.8.egg/orangebox/parser.py", line 77, in load
  File "/usr/local/lib/python3.8/dist-packages/orangebox-0.2.0-py3.8.egg/orangebox/reader.py", line 59, in __init__
  File "/usr/local/lib/python3.8/dist-packages/orangebox-0.2.0-py3.8.egg/orangebox/reader.py", line 82, in set_log_index
  File "/usr/local/lib/python3.8/dist-packages/orangebox-0.2.0-py3.8.egg/orangebox/reader.py", line 146, in _build_field_defs
RuntimeError: No predictor found for 10

The log decodes in blackbox_decode fine and produces the csv, gps csv & gpx files

Platform is Ubuntu 20.04 and install was from source.

log attached and renamed as .txt for attachment (sorry if there is a better way I cant see it). 
[BTFL_BLACKBOX_LOG_20200827_190605.txt](https://github.com/atomgomba/orangebox/files/5140494/BTFL_BLACKBOX_LOG_20200827_190605.txt)

**Comment by atomgomba** [comment]
Thank you for creating an issue! This is related to the lack of support for encoded GPS data which is a known issue. This log file will come in handy when implemented GPS frames decoding! :+1:

**Comment by atomgomba** [comment]
Closing since it is the same as #2
